r_tc_user:
    resource: "@lostBookUserBundle/Resources/config/routing.yml"
    prefix:   /

r_tc:
    resource: "@lostBookBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
oneup_uploader:
    resource: .
    type: uploader

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
